# Python 주요 패키지 소개

## numpy

In [1]:
import numpy as np 

## 1차원 벡터 생성하기

In [2]:
ar1 = np.array([1, 2, 3]) 

In [3]:
type(ar1)

numpy.ndarray

In [4]:
print(ar1)

[1 2 3]


In [5]:
ar1.ndim

1

In [6]:
ar1.shape

(3,)

In [7]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(1, 21, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

## 벡터 원소의 형 변환

In [10]:
a = [1, 2, 3.0]

In [11]:
ar = np.array(a)

In [12]:
print(ar)

[1. 2. 3.]


In [13]:
ar.astype(int)

array([1, 2, 3])

In [14]:
ar.astype(str)

array(['1.0', '2.0', '3.0'], dtype='<U32')

## 2차원 행렬 생성하기

In [15]:
ar2 = np.array([[1, 2, 3], 
                [4, 5, 6]]) 

In [16]:
type(ar2)

numpy.ndarray

In [17]:
print(ar2)

[[1 2 3]
 [4 5 6]]


In [18]:
ar2.ndim

2

In [19]:
ar2.shape

(2, 3)

In [20]:
np.zeros([2, 3], dtype = 'int')

array([[0, 0, 0],
       [0, 0, 0]])

In [21]:
np.zeros([3, 2], dtype = 'float')

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## 배열의 차원 변환

In [22]:
ar1 = np.arange(12)

In [23]:
print(ar1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [24]:
ar1.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [25]:
ar1.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
ar1.reshape(3, 5)  # 에러가 발생합니다. 

ValueError: cannot reshape array of size 12 into shape (3,5)

In [31]:
ar2 = ar1.reshape(4, 3)

In [32]:
print(ar2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [33]:
ar2.reshape(6, -1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

## 배열의 인덱싱

In [34]:
ar1 = np.arange(6)

In [35]:
ar1[1]

1

In [36]:
ar2 = ar1.reshape(2, 3)

In [37]:
ar2[0, 0]

0

In [38]:
ar2[0, 1]

1

## 배열의 슬라이싱

In [39]:
ar1[:2]

array([0, 1])

In [40]:
ar1[2:]

array([2, 3, 4, 5])

In [41]:
ar1[:]

array([0, 1, 2, 3, 4, 5])

In [42]:
ar2[0:1, 0:1]

array([[0]])

In [43]:
ar2[:, 1:3]

array([[1, 2],
       [4, 5]])

In [56]:
ar2[:, :]

array([[0, 1, 2],
       [3, 4, 5]])

## 배열의 원소 정렬하기

In [ ]:
ar3 = np.array([1, 5, 6, 3, 4, 7, 2]) 

In [ ]:
print(ar3)

In [ ]:
np.sort(ar3)

In [ ]:
print(ar3)

In [ ]:
ar3.sort()

In [ ]:
print(ar3)

In [ ]:
ar3[::-1]

## 벡터의 덧셈, 뺄셈 연산

In [ ]:
a = np.array([1, 1])
b = np.array([-1, 1])

In [ ]:
a + b

In [ ]:
a - b

In [ ]:
c = [1, 1]
d = [-1, 1]

In [ ]:
c + d

## 벡터의 스칼라배 연산

In [ ]:
a * 0

In [ ]:
a * 2

In [ ]:
b * 2

In [ ]:
(a + b) * 2

In [ ]:
a * 2 + b * 2

In [ ]:
a * (2 + 3)

In [ ]:
a * 2 + a * 3

## 벡터의 내적

In [ ]:
def innerProd(x, y):
    return sum(x*y)

In [ ]:
innerProd(a, b)

In [ ]:
np.dot(a, b)

## 벡터의 크기

In [ ]:
def vecLen(x):
    return sum(x**2)**(1/2)

In [ ]:
vecLen(a)

In [ ]:
np.dot(a, a)**(1/2)

In [ ]:
innerProd(a, b) / (vecLen(a) * vecLen(b))

## 행렬의 덧셈, 뺄셈 연산

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 3], [2, 4]])
C = np.ones([2, 2])

In [ ]:
A + B

In [ ]:
A - B

In [ ]:
(A + B) + C

In [ ]:
A + (B + C)

## 행렬의 스칼라배 연산

In [ ]:
A * 0

In [ ]:
A * 2

In [ ]:
B * 2

In [ ]:
A * 2 + B * 2

In [ ]:
(A + B) * 2

In [ ]:
A * (2 + 3)

In [ ]:
A * 2 + A * 3

## 행렬의 곱셈 연산

In [ ]:
np.matmul(A, B)

In [ ]:
np.matmul(B, A)

## 역행렬

In [ ]:
import numpy.linalg as lin

In [ ]:
AI = lin.inv(A)

In [ ]:
np.matmul(A, AI)

In [ ]:
np.matmul(AI, A)

## 행렬식

In [ ]:
lin.det(A)

In [ ]:
lin.det(B)

In [ ]:
M = np.array([[1, 2], [2, 4]])

In [ ]:
lin.det(M)

## 가상의 키(신장) 데이터 생성

In [ ]:
np.random.seed(seed = 1234)

In [ ]:
heights = np.random.normal(170, 10, size = 100)

## 기술 통계량

In [ ]:
np.mean(heights)

In [ ]:
np.median(heights)

In [ ]:
np.min(heights)

In [ ]:
np.max(heights)

In [ ]:
np.max(heights) - np.min(heights)

In [27]:
np.percentile(heights, 25)

NameError: name 'heights' is not defined

In [ ]:
np.percentile(heights, 75)

In [ ]:
np.percentile(heights, 75) - np.percentile(heights, 25)

In [ ]:
np.percentile(heights, [0, 25, 50, 75, 100])

In [ ]:
np.var(heights)

In [ ]:
np.std(heights)

In [ ]:
math = [82, 58, 64, 76, 55, 89, 98, 92, 46, 87]
korean = [98, 78, 87, 78, 72, 87, 99, 83, 76, 90]

In [ ]:
np.cov(math, korean)

In [ ]:
np.corrcoef(math, korean)

## [참고] 데이터 표준화

In [ ]:
import scipy.stats as stats

In [ ]:
scaled = stats.zscore(heights)

In [ ]:
np.mean(scaled)

In [ ]:
np.std(scaled)

## 도수분포표

In [ ]:
bins = np.arange(130, 211, 10)

In [ ]:
hist, bins = np.histogram(heights, bins)

In [ ]:
print(hist)

In [ ]:
total = len(heights)

In [ ]:
prop = hist / total

In [ ]:
print(prop)

In [ ]:
sum(prop)

# matplotlib

## 히스토그램

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.hist(heights, bins)
plt.xlabel('Height(cm)', fontsize = 14)
plt.xticks(fontsize = 12)
plt.yticks(fontsize = 12)
plt.show()

## 상자수염그림

In [ ]:
plt.boxplot(heights, sym = 'bo')
plt.title('Boxplot of Heights', fontsize = 16)
plt.xticks([1], ['Heights'], fontsize = 12)
plt.show()

## 산점도

In [ ]:
plt.scatter(math, korean, color = 'b', marker = 'o')
plt.title('Scatter plot', fontsize = 16)
plt.xlabel('Math', fontsize = 14)
plt.ylabel('Korean', fontsize = 14)
plt.show()

# pandas

In [ ]:
import pandas as pd

## 1차원 시리즈 생성하기

In [ ]:
sr = pd.Series([1, 3, 5, 7, 9])

In [ ]:
print(sr)

In [ ]:
print(sr.values)

In [ ]:
print(sr.index)

In [ ]:
sr.index = ['a', 'b', 'c', 'd', 'e']
print(sr)

In [ ]:
sr = pd.Series([1, 3, 5, 7, 9], index = ['a', 'b', 'c', 'd', 'e'])
print(sr)

In [ ]:
sr = pd.Series({'a':1, 'b':3, 'c':5, 'd':7, 'e':9})
print(sr)

## 시리즈의 인덱싱과 슬라이싱

In [ ]:
sr[0]

In [ ]:
sr['a']

In [ ]:
sr[[1, 2]]

In [ ]:
sr[['b', 'c']]

In [ ]:
sr[:2]

In [ ]:
sr[2:]

In [ ]:
sr[sr >= 3]

## 시리즈의 값 변경

In [ ]:
sr + 1

In [ ]:
sr * 2

In [ ]:
sr[sr >= 5] = ['가', '나', '다']

In [28]:
sr[sr == '다'] = np.nan

NameError: name 'sr' is not defined

In [ ]:
sr.fillna(0)

In [ ]:
sr.dropna()

In [ ]:
nr = pd.Series('라', index = ['f'])

In [ ]:
sr = sr.append(nr)
print(sr)

## 2차원 데이터프레임 생성하기

In [ ]:
df = pd.DataFrame([[85, 79, 92], [57, 76, 69], [98, 89, 74]], 
                  index = [1, 2, 3], 
                  columns = ['A반', 'B반', 'C반']) 

In [ ]:
print(df) 

In [ ]:
df = pd.DataFrame({'A반':[85, 79, 92], 'B반':[57, 76, 69], 'C반':[98, 89, 74]},
                  index = [1, 2, 3]) 

In [ ]:
print(df) 

## [참고] 파일과 폴더 다루기

In [ ]:
import os, shutil 

In [ ]:
os.getcwd()

In [ ]:
os.mkdir('../temp')

In [ ]:
shutil.copy('test.txt', 'test_new.txt')

In [ ]:
shutil.copy2('test.txt', '../temp')

In [ ]:
shutil.move('test_new.txt', '../temp')

In [ ]:
os.chdir('../temp')

In [ ]:
os.rename('test.txt', 'test_old.txt')

In [ ]:
os.listdir()

In [ ]:
os.remove('test_old.txt')

In [ ]:
for i in os.listdir():
    os.remove(i)

In [ ]:
os.chdir('../') 

In [ ]:
os.getcwd()

In [ ]:
os.rmdir('./temp')

In [ ]:
# shutil.rmtree('./temp')

## 엑셀 파일을 데이터프레임으로 불러오기

In [ ]:
df = pd.read_excel('./data/2019_KBO_Win.xlsx', 
                   sheet_name = 'Sheet1')

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df.index

In [ ]:
df.dtypes

## 데이터프레임 다루기 : 인덱스로 일부 확인

In [ ]:
df.head(5)

In [ ]:
df.tail(5)

In [ ]:
df.iloc[0]

In [ ]:
df.iloc[0:10]

In [ ]:
df.iloc[0:10, 0:12]

In [ ]:
df.loc[0]

In [ ]:
df.loc[0:10]

In [ ]:
df.loc[0:10, '선수명':'도루']

## 데이터프레임 다루기 : 일부 선택 또는 삭제

In [ ]:
df.팀명

In [ ]:
df['팀명'] = pd.Categorical(df['팀명'])

In [29]:
df[['선수명', '팀명']]

NameError: name 'df' is not defined

In [ ]:
df.drop(range(100, 300), axis = 0)

In [ ]:
df.drop('BABIP', axis = 1)
print(df)

In [ ]:
df.drop('BABIP', axis = 1, inplace = True)
print(df)

In [ ]:
df.drop(['wOBA', 'WAR'], axis = 1, inplace = True)
print(df)

In [ ]:
df.drop(range(0, 12), axis = 1)  # 에러가 발생합니다. 

## 데이터프레임 다루기 : 새로운 컬럼 생성

In [ ]:
df['팀명'].value_counts()

In [ ]:
df['닉네임'] = '별명'
print(df)

In [ ]:
df['타수*'] = df['타석'] - df['타수']
print(df)

In [ ]:
df['타율*'] = np.round(df['안타'] / df['타수'], 3)
print(df)

In [ ]:
df['OPS*'] = df['출루율'] + df['장타율']
print(df)

In [ ]:
df = df.loc[ : , '선수명':'OPS']
print(df)

In [ ]:
df.isna().sum()

In [ ]:
df = df.dropna()
df.shape

## 데이터프레임 다루기 : 조건을 만족하는 행 확인

In [ ]:
df = df[df.타석 >= 144 * 3.1]
print(df)

In [ ]:
df = df.reset_index().drop('index', axis = 1)

In [ ]:
df.sort_values(by = '안타', ascending = False).head(5)

In [ ]:
df.sort_values(by = ['홈런', '삼진'], ascending = False)

In [ ]:
df.sort_values(by = ['홈런', '삼진'], ascending = [False, True])

In [ ]:
df[(df.홈런 >= 20) & (df.OPS >= 0.9)]

In [ ]:
df[(df.홈런 >= 20) & (df.도루 >= 20)]

## 다른 데이터 타입으로 변경하기

In [ ]:
df.values

In [ ]:
df.values.tolist()

In [ ]:
df.to_dict('list')

In [ ]:
df.to_excel('./data/test.xlsx', sheet_name = '2019_KBO')

## [참고] csv, txt 파일 입출력

In [ ]:
df.to_csv('./data/test.csv', index = None)

In [ ]:
df1 = pd.read_csv('./data/test.csv')

In [ ]:
df1.head(5)

In [ ]:
df.to_csv('./data/test.txt', sep = ' ', index = None) 

In [ ]:
df2 = pd.read_csv('./data/test.txt', sep = ' ')

In [ ]:
df2.head(5)

## scikit-learn

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz 
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score
from sklearn.metrics import roc_curve, roc_auc_score

## 분석 데이터 준비

In [ ]:
iris = load_iris()
print(iris)

In [ ]:
type(iris)

In [ ]:
iris.data

In [ ]:
iris.target

In [ ]:
iris.target_names

In [30]:
iris.feature_names

NameError: name 'iris' is not defined

In [ ]:
df = pd.DataFrame(data = iris.data, 
                  columns = iris.feature_names)
print(df)

In [ ]:
df['label'] = iris.target
print(df)

In [ ]:
df = df[df.label != 2]
print(df)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 0:4], 
                                                    df.iloc[:, 4],
                                                    test_size = 0.3, 
                                                    random_state = 1)

## 분류모형 적합 및 추정값 생성

In [ ]:
tree = DecisionTreeClassifier(random_state = 1, 
                              criterion = 'gini',
                              max_depth = 10, 
                              min_samples_leaf = 1)

In [ ]:
tree.fit(X_train, y_train)

In [ ]:
tree.get_depth()

In [ ]:
tree.get_n_leaves()

In [ ]:
tree.get_params()

## 나무모형 시각화

In [ ]:
export_graphviz(tree, out_file = './data/tree_iris.dot', 
                class_names = ['Setosa', 'Versicolor'], 
                feature_names = iris.feature_names, 
                impurity = False, 
                filled = True)

In [ ]:
import graphviz

In [ ]:
with open('./data/tree_iris.dot') as file:
    dot_graph = file.read()

In [ ]:
display(graphviz.Source(dot_graph))

## 나무모형 이미지로 저장

In [ ]:
os.mkdir('./image')

In [ ]:
import pydot

In [ ]:
(graph,) = pydot.graph_from_dot_file('./data/tree_iris.dot')
graph.write_png('./image/tree_iris.png')

In [ ]:
from IPython.display import Image

In [ ]:
Image('./image/tree_iris.png')

## 변수의 중요도 시각화

In [ ]:
n_feature = iris.data.shape[1]

In [ ]:
importance = tree.feature_importances_

In [ ]:
plt.barh(np.arange(n_feature), importance, align = 'center')
plt.yticks(np.arange(n_feature), iris.feature_names)
plt.xlabel('Feature Importances')
plt.ylabel('Feature')
plt.ylim(-1, n_feature)
plt.show()

In [ ]:
plt.barh(np.arange(n_feature), importance, align = 'center')
plt.yticks(np.arange(n_feature), iris.feature_names)
plt.xlabel('Feature Importances')
plt.ylabel('Feature')
plt.ylim(-1, n_feature)
plt.savefig('./image/varImp.png', bbox_inches = 'tight')

In [ ]:
Image('./image/varImp.png')

## 모형의 성능 평가하기

In [ ]:
pred = tree.predict(X_test)

In [ ]:
confusion_matrix(y_test, pred)

In [ ]:
accuracy_score(y_test, pred)

In [ ]:
precision_score(y_test, pred)

In [ ]:
recall_score(y_test, pred)

In [ ]:
f1_score(y_test, pred)

## ROC 곡선 시각화 및 AUC 확인

In [ ]:
proba = tree.predict_proba(X_test)[:, 1]

In [ ]:
fprs, tprs, thresholds = roc_curve(y_test, proba)

In [ ]:
plt.plot(fprs, tprs, label = 'ROC')
plt.plot([0, 1], [0, 1], 'r--', label = 'Random')
plt.xlabel('FPR'); plt.ylabel('TPR')
plt.legend(loc = 'lower right')
plt.show()

In [ ]:
roc_auc_score(y_test, pred)

## End of Document